---
title: "PubMed Article Searching in R"
subtitle: "A simple practical user guides for publication statistics"
author: "Teresia Mrema-Buza, A Bioinformatics and Data Science Enthusiast"
date: "Updated on `r Sys.Date()`"
site: bookdown::bookdown_site
knit: bookdown::render_book
output:
  bookdown::bs4_book:
    includes:
      in_header:
    template: bs4_template.html
        
  bookdown::gitbook:
    includes:
      in_header: header.html
    config: 
      toc:
       collapse: 
      search: yes
      fontsettings:
        size: 2
    split_by: section
    split_bib: no
    df_print: paged
    number_sections: true
documentclass: book
classoption: openany
bibliography:
- library/packages.bib
- library/bibliograph.bib
citation_package:
- natbib
- biblatex
- amsplain
colorlinks: true
css:
  - style.css
always_allow_html: true
fig_caption: true
fontsize: 12pt
geometry: margin=1in
indent: false
keep_tex: true
link-citations: true
mainfont: Times New Roman
biblio-style: apalike
spacing: double
description: |
  This guide provides integrated and highly curated solutions for achieving better results.
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)

## Create Object Folder 
if (!dir.exists("library")) {dir.create("library")}
if (!dir.exists("data")) {dir.create("data")}
if (!file.exists("library/bibliograph.bib")) {file.create("library/bibliograph.bib")}

# source(file = "R/common.R")

htmltools::tagList(rmarkdown::html_dependency_font_awesome())

knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  comment = NA,
  fig.path='./figures/',
  fig.show='asis',
  dev = 'png',
  fig.align='center',
  out.width = "80%",
  out.height = "40%",
  fig.width = 7,
  fig.asp = 0.618,
  fig.show = "asis"
)
```

# Getting Started withSearching PubMed Articles {#pubmed-search}

```{r pkgbiblib, include=FALSE}
knitr::write_bib(c(.packages(), 'base','bookdown','rmarkdown','tidyverse'), 'library/packages.bib')
```


## Load libraries
```{r}
library(rentrez)
library(glue)
library(tidyverse, suppressPackageStartupMessages)
library(DiagrammeR)
library(DiagrammeRsvg)
library(tictoc)
```

## Manual search workflow
```{r workflow}
mermaidgraph <- mermaid("graph TD

subgraph SEARCHING PUBMED DATABASE
A[NCBI PubMed Database<br>https://pubmed.ncbi.nlm.nih.gov/] --> B[Search Term]
B --> |Search Results| C[Indexed Papers in PubMed]
end
subgraph SEARCH RESULTS
C --> |Download results| D{Results by Year in CSV format}
D --> |Filename| E[PubMed_Timeline_Results_by_Year.csv]
E --> F[Save file in data directory]
end

F -.-> G[Further Analysis in R or Python]

", height = 500, width = 300)

mermaidgraph

```


## Code availability {-}
The code that generated this guide is available at a public [GitHub repository](https://github.com/DataInsights/pubmed-tracking/) or via a [GH-Page](https://DataInsights.github.io/pubmed-tracking/).




